name: Run Playwright Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-donobu-flows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Install Dependencies
        run: npm ci && npx playwright install --with-deps

      - name: Run Playwright Tests
        id: run_tests
        continue-on-error: true
        env:
          SELF_HEAL_TESTS_ENABLED: true
          DONOBU_API_KEY: ${{ secrets.DONOBU_API_KEY }}
        run: npx donobu test

      - name: Generate GitHub Workflow Summary
        if: always()
        run: |
          npm exec playwright-json-to-markdown test-results/playwright-report.json >> $GITHUB_STEP_SUMMARY

      - name: Save Test Reports as Artifacts
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 3

      - name: Post to Slack
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -n "$SLACK_WEBHOOK_URL" ]; then
            WORKFLOW_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            SLACK_PAYLOAD=$(npm exec playwright-json-to-slack-json -- --report-url "$WORKFLOW_URL" < "test-results/playwright-report.json")
            curl --header 'Content-type: application/json' --data "$SLACK_PAYLOAD" "$SLACK_WEBHOOK_URL"
          else
            echo "SLACK_WEBHOOK_URL secret not present, skipping Slack notification."
          fi

      # Create a self-healing PR only when this workflow was not triggered by a pull-request.
      - name: Create Pull Request for Test Fixes (if any)
        if: ${{ github.event_name != 'pull_request' }}
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Fix failing Playwright tests"
          title: "[Fixed] Playwright tests"
          body: "Fix failing Playwright tests"
          branch: fix-playwright-tests-for-${{ github.ref_name }}
          base: ${{ github.ref_name }}